# Load ViFactCheck

In [1]:
import numpy as np
import pandas as pd

In [2]:
vifactcheck_df = pd.read_csv('../../data/vifactcheck/vifactcheck_extract_data.csv')
vifactcheck_df.head()

,id,statement,context,label
0,0,"Phó Thủ tướng Trần Hồng Hà thay mặt Chính phủ,...","(Chinhphu.vn) - Đây là mong muốn, gửi gắm của ...",0
1,1,Hành vi của Tô Văn Hải là cho phép người khác ...,"Ngày 24/3, Cơ quan Cảnh sát điều tra Công an t...",0
2,2,SAWACO thông báo tạm ngưng cung cấp nước để th...,(PLO)- Theo Tổng Công ty Cấp nước Sài Gòn (SAW...,1
3,3,"CLB luôn chuẩn bị rất kỹ lưỡng, chỉn chu chươn...","Với khoảng 200 thành viên, UEF Warm Hugs Club ...",2
4,4,"ILA tiếp nhận và hỗ trợ học sinh miễn phí, Bé ...","Đi qua 2 năm dịch bệnh đầy thử thách, nhưng ch...",2

In [14]:
# Save label 0 and 1 to a separate csv file
vifactcheck_df[vifactcheck_df.label.isin([0, 1])].to_csv('../../data/vifactcheck/vifactcheck_relevant_pairs.csv', index=False)

In [15]:
vifactcheck_df[vifactcheck_df.label.isin([0, 1])].shape

(4885, 4)

In [6]:
import json

vifactcheck_unique = vifactcheck_df['context'].unique()

# Save unique contexts to a JSON file with idx having prefix 'c_'
with open('../../data/vifactcheck_unique_contexts.json', 'w') as f:
    json.dump({f'c_{i}': context for i, context in enumerate(vifactcheck_unique)}, f, indent=4)

# EDA

In [7]:
import json

with open('../../data/vifactcheck/extracted_keywords_20251001-162315.json', 'r') as f:
    extracted_keywords = json.load(f)

extracted_keywords

{'c_0': 'Phó Thủ tướng Trần Hồng Hà Liên hoan Truyền hình toàn quốc 41 tối 18/3 Hải Phòng văn hóa Việt Nam tác phẩm truyền hình COVID-19 truyền thông công nghệ số Đảng Nhà nước',
 'c_1': 'Tô Văn Hải, 1970, Bình Dương, tội Gây ô nhiễm môi trường, chôn lấp, chất thải rắn, 642.070 kg, ngày 21/3/2023, Cơ sở nuôi trồng thủy sản Thăng Tiến, ngày 21/12/2016, ngày 7/11/2017, tháng 5/2020, ngày 18/9/2020, ngày 7/12/2022, khởi tố vụ án, Điều 235 Bộ luật Hình sự, 7 năm tù, 20 tỷ đồng.',
 'c_2': 'cúp nước bảo trì Nhà máy nước Tân Hiệp SAWACO 22h 25-3 4h 26-3 quận 6 8 12 Gò Vấp Tân Bình Tân Phú Bình Tân Hóc Môn Bình Chánh xe bồn',
 'c_3': 'UEF Warm Hugs Club 2015 "Nắng ấm biên cương" 6 mùa NABC mùa 4 mùa NABC 5 130 triệu đồng',
 'c_4': 'ILA giáo dục mở rộng chi nhánh tháng 3.2023 tháng 2.2022 25 năm kinh nghiệm kỹ năng tư duy thế kỷ 21 project-based learning hệ sinh thái giáo dục cuối năm 2022 đầu năm 2023 dự án chuyển đổi số 2022 đầu năm 2024 học bổng cộng đồng',
 'c_5': 'nghệ sĩ Oscar 2023 cảm ơn cấu trúc Dương Tử Quỳnh Everything Everywhere All at Once Quan Kế Huy Brendan Fraser The Whale lời cảm ơn trang trọng công cộng ngữ pháp động từ tính từ giới từ',
 'c_6': 'Lý Hoàng Nam, chiều 24-3, tứ kết, M25 Lucknow, chiến thắng 2-0, Vishwakarma Siddharth, vào bán kết, tay vợt Việt Nam.',
 'c_7': '27/2 VFF công bố HLV trưởng Việt Nam Philippe Troussier 3 năm 1/3/2023 31/7/2026 dẫn dắt Đội tuyển Việt Nam U22 U23 bóng đá',
 'c_8': 'Lễ hội Thanh niên Tháng Thanh niên Ngày thành lập Đoàn TNCS Hồ Chí Minh 26.3 24 - 26.3 văn hóa nghệ thuật công nghệ cộng đồng hội thảo không gian trải nghiệm tuyến đường ánh sáng văn hóa trẻ ẩm thực startup trẻ nghệ thuật sáng tạo Tháng ba sách trẻ công nghệ số con đường Thanh niên',
 'c_9': 'Giáo viên tiểu học Học thông qua chơi thúc đẩy sáng tạo kỹ năng thiết yếu VVOB Bộ GD-ĐT tài liệu bồi dưỡng cán bộ quản lý năm 2021 dự án iPLAY 2020-2023 Quỹ LEGO 2023 mục tiêu GDPT 2018'}

In [13]:
with open('../../data/vifactcheck/vifactcheck_unique_contexts.json', 'r') as f:
    unique_contexts = json.load(f)

# First 10 entries
list(unique_contexts.items())[:10]

[('c_0',
  '(Chinhphu.vn) - Đây là mong muốn, gửi gắm của Phó Thủ tướng Trần Hồng Hà đến những người làm truyền hình tại lễ bế mạc Liên hoan Truyền hình toàn quốc lần thứ 41, tối 18/3, tại TP. Hải Phòng. Phó Thủ tướng Trần Hồng Hà: Các tác phẩm truyền hình đã vun đắp, làm giàu cho nền văn hóa Việt Nam tiên tiến, đậm đà bản sắc dân tộc, góp phần tạo dựng môi trường văn hóa lành mạnh và xây dựng con người Việt Nam nhân cách, trách nhiệm, hội nhập - Ảnh: VGP/Minh Khôi Tham dự lễ bế mạc còn có Bí thư Trung ương Đảng, Trưởng Ban Tuyên giáo Trung ương Nguyễn Trọng Nghĩa, lãnh đạo các bộ, ngành Trung ương, địa phương, đại diện các đài truyền hình, đơn vị sản xuất chương trình truyền hình, cùng đông đảo cán bộ, phóng viên, biên tập viên, nghệ sĩ, diễn viên hoạt động trong lĩnh vực truyền hình… Thay mặt Chính phủ, Thủ tướng Chính phủ, Phó Thủ tướng Trần Hồng Hà chúc mừng Đài Truyền hình Việt Nam, Đài truyền hình các tỉnh, thành phố trên cả nước, các đơn vị sản xuất truyền hình và TP. Hải Phòng đã tổ chức rất thành công sự kiện quan trọng này sau 2 năm gián đoạn do đại dịch COVID-19. Phó Thủ tướng nhấn mạnh, với lợi thế kết hợp cả hình ảnh và âm thanh, truyền hình tiếp tục là một trong các loại hình truyền thông có sức ảnh hưởng trực tiếp và lan tỏa rộng rãi nhất. Từng bản tin, chương trình và các tác phẩm truyền hình đã mang đến cho khán giả trong nước và quốc tế nhịp đập, hơi thở của đời sống xã hội Việt Nam; khơi dậy mạnh mẽ tinh thần đoàn kết, anh dũng cho toàn quân, toàn dân trong công cuộc kháng chiến; tạo nguồn cảm hứng đổi mới, sáng tạo cho sự nghiệp dựng xây đất nước phồn vinh, hạnh phúc. Đồng thời, trên mặt trận văn hóa, tư tưởng, các tác phẩm truyền hình đã vun đắp, làm giàu cho nền văn hóa Việt Nam tiên tiến, đậm đà bản sắc dân tộc, góp phần tạo dựng môi trường văn hóa lành mạnh và xây dựng con người Việt Nam nhân cách, trách nhiệm, hội nhập. Với lòng yêu nghề, nhiệt huyết, trong nhiều năm qua, những người làm truyền hình trên cả nước đã mang đến các tác phẩm truyền hình chất lượng cao, giá trị tốt, là món ăn tinh thần không thể thiếu đối với khán giả trong và ngoài nước. Bí thư Trung ương Đảng, Trưởng Ban Tuyên giáo Trung ương Nguyễn Trọng Nghĩa, Phó Thủ tướng Trần Hồng Hà và lãnh đạo các bộ, ngành Trung ương, địa phương dự lễ bế mạc Liên hoan Truyền hình toàn quốc lần thứ 41 - Ảnh: VGP/Minh Khôi Trải qua 41 kỳ, Liên hoan Truyền hình toàn quốc đã trở thành ngày hội của những người làm truyền hình trên cả nước, là diễn đàn hữu ích dành cho những người làm báo hình nói riêng và báo chí nói chung cùng trao đổi, học hỏi, chia sẻ, tăng cường tình đoàn kết, đồng thời được khán giả cả nước mong đợi. Sau thời gian gián đoạn do đại dịch COVID-19, Liên hoan truyền hình toàn quốc đã trở lại với nhiều ấn tượng to lớn, quy tụ số lượng tác phẩm tham gia tranh giải cao kỷ lục, gồm 714 tác phẩm với 11 thể loại và được thể hiện đa dạng, phong phú trên nhiều nền tảng, phù hợp với xu thế phát triển mạnh mẽ của công nghệ số. Đây là minh chứng sống động cho thấy ngành truyền hình Việt Nam đang vươn mình mạnh mẽ, bắt kịp với xu thế toàn cầu nhưng vẫn giữ được nét độc đáo. Phó Thủ tướng Trần Hồng Hà, Bộ trưởng Bộ TT&TT Nguyễn Mạnh Hùng trao giải Vàng cho phim truyền hình xuất sắc nhất; nam, nữ diễn viên phim truyền hình xuất sắc nhất - Ảnh: VGP/Minh Khôi Các tác phẩm tham gia Liên hoan đã bám sát các vấn đề thời sự, phản ánh sâu sắc, sinh động hơi thở cuộc sống, mang đậm bản sắc vùng miền, được xây dựng công phu, chất lượng, có tính chiến đấu cao, giá trị nhân văn sâu sắc, có sức lan tỏa, tác động tích cực trong đời sống xã hội. Những hình ảnh, âm thanh trong các tác phẩm để lại nhiều ấn tượng sâu sắc, chân thực, chạm tới cảm xúc của khán giả, từ đó định hướng dư luận xã hội, phản biện xã hội, tăng cường niềm tin của nhân dân vào Đảng, Nhà nước; tuyên truyền về đấu tranh, phản bác quan điểm sai trái, thông tin xấu độc, bảo vệ nền tảng tư tưởng của Đảng; đóng góp quan trọng vào sự nghiệp xây dựng và bảo vệ Tổ quốc. Những người làm báo hình có bản lĩnh, ý chí, quyết tâm rất cao, dám dấn thân trong điều kiện tác nghiệp ngặt nghèo, khó khăn, thậm chí nguy hiểm. "Có những tác giả, tác phẩm được lựa chọn để vinh danh, nhưng còn rất nhiều tác giả, tác phẩm truyền hình khác vẫn đang làm công việc thầm lặng để đóng góp chung cho đất nước trong giai đoạn khó khăn thời kỳ dịch COVID-19", Phó Thủ tướng nói và trân trọng cảm ơn những nỗ lực, cố gắng của đội ngũ những người làm báo hình, các tổ chức, cơ quan báo chí trên cả nước đã đồng hành, cổ vũ, tạo đồng thuận xã hội, cùng đất nước, nhân dân vượt qua khó khăn, phục hồi và phát triển kinh tế - xã hội. Các tác phẩm tham dự liên hoan sẽ tạo sức lan tỏa trong toàn xã hội và động lực sáng tạo cho đội ngũ làm báo chí, đặc biệt là báo hình. Bí thư Trung ương Đảng, Trưởng ban Tuyên giáo Trung ương Nguyễn Trọng Nghĩa và Tổng Giám đốc Đài Truyền hình Việt Nam Lê Ngọc Quang trao giải Vàng thể loại Phim tài liệu Phó Thủ tướng cũng trao đổi về những cơ hội, thuận lợi và cả khó khăn, thách thức của truyền hình trong kỷ nguyên toàn cầu hóa và hội nhập quốc tế sâu rộng; sự phát triển mạnh mẽ của khoa học công nghệ; sự chuyển động nhanh của thế giới; thực tiễn đổi mới, phát triển năng động của đất nước hiện nay. Điều đó đặt ra yêu cầu cần phải phát huy hơn nữa tinh thần đổi mới, sáng tạo và hội nhập của đội ngũ người làm báo hình của Việt Nam để khẳng định vị thế, đáp ứng được yêu cầu phát triển của đất nước và thị hiếu ngày càng cao của khán giả trong bối cảnh cạnh tranh gay gắt của các loại hình thông tin, truyền thông, đặc biệt là từ nước ngoài. Kinh nghiệm thành công trong thúc đẩy thương mại và đầu tư toàn cầu của các nền kinh tế lớn trong khu vực và thế giới chính là phát huy đầy đủ vai trò quan trọng và ưu thế của truyền hình trong việc tăng cường sức mạnh mềm của quốc gia. Phó Thủ tướng nêu rõ: Hơn bao giờ hết, những người làm báo hình Việt Nam cần ý thức được trách nhiệm của mình với tư cách là những sứ giả cho sức mạnh mềm của Việt Nam; mang những giá trị văn hóa tốt đẹp "chân - thiện - mỹ" của dân tộc đến với khán giả trong nước và quốc tế, góp phần nâng cao sức mạnh tổng hợp quốc gia. Một mặt, góp phần giữ gìn và bồi đắp nền văn hóa dân tộc, xây dựng con người Việt Nam mới trong kỷ nguyên số, xã hội số và văn hóa số, mặt khác thúc đẩy văn hóa, thương hiệu và sản phẩm Việt Nam ra với thế giới. Tổng Biên tập Báo Nhân dân Lê Quốc Minh, Bí thư Thành ủy Hải Phòng Lê Tiến Châu trao giải Vàng cho các tác phẩm truyền hình thuộc thể loại Tiếng dân tộc thiếu sổ, Đối thoại - Tọa đàm, Chuyên đề - Khoa giáo - Ảnh: VGP/Minh Khôi Phó Thủ tướng cũng khẳng định, Đảng, Nhà nước sẽ luôn dành sự quan tâm đặc biệt bằng các cơ chế, chính sách phù hợp; quan tâm đầu tư, khơi thông các nguồn lực xã hội, phát triển không gian văn hóa sáng tạo, đẩy mạnh chuyển đổi số, đãi ngộ, tôn vinh tài năng và cống hiến. Tạo lập môi trường để những người làm văn hóa, nghệ thuật, trong đó có truyền hình, phát huy sức sáng tạo có những tác phẩm tầm cỡ, phản ánh được sâu sắc hiện thực đổi mới vĩ đại của đất nước theo tinh thần của Nghị quyết Đại hội lần thứ XIII của Đảng và phát biểu chỉ đạo quan trọng của Tổng Bí thư Nguyễn Phú Trọng tại Hội nghị Văn hóa toàn quốc; phát triển truyền hình thành ngành công nghiệp hiện đại, hội nhập ngang tầm các nước tiên tiến trong khu vực. "Với sự trưởng thành, vững vàng về bản lĩnh chính trị, phẩm chất đạo đức và trình độ nghiệp vụ chuyên môn ngày càng chuyên nghiệp, đội ngũ phóng viên, biên tập viên, kỹ thuật viên làm truyền hình luôn bám sát hơi thở của cuộc sống; tận dụng tối đa những chất liệu, công nghệ mới để có những sản phẩm với chất lượng cao, có tầm vóc, đáp ứng nhu cầu ngày càng đa dạng của khán giả. Đồng thời, hoàn thành sứ mệnh là tiếng nói của Đảng, của Nhà nước và nhân dân; phát huy sự đồng thuận trong xã hội, củng cố khối đại đoàn kết toàn dân tộc, đóng góp ngày càng hiệu quả vào thực hiện thắng lợi nhiệm vụ xây dựng và bảo vệ Tổ quốc, truyền cảm hứng, khơi dậy mạnh mẽ khát vọng phát triển đất nước hùng cường, thịnh vượng", Phó Thủ tướng tin tưởng và mong muốn những người làm truyền hình Việt Nam không ngừng lớn mạnh, luôn giữ được lửa nghề, tâm sáng, bút sắc, tiếp tục "Tôn vinh đam mê, khuyến khích đổi mới, cập nhật xu hướng", mang tới những sản phẩm tốt nhất cho khán giả. Minh Khôi'),
 ('c_1',
  'Ngày 24/3, Cơ quan Cảnh sát điều tra Công an tỉnh Bình Dương cho biết, đơn vị vừa thực hiện lệnh bắt bị can để tạm giam đối với Tô Văn Hải (sinh năm 1970, hộ khẩu thường trú xã Phước Hòa, huyện Phú Giáo) để điều tra làm rõ tội “Gây ô nhiễm môi trường” theo điểm d khoản 3 Điều 235, Bộ luật Hình sự. Theo đó, Tô Văn Hải là người trực tiếp điều hành, quản lý Cơ sở nuôi trồng thủy sản Thăng Tiến đã có hành vi cho phép người khác đổ, thải chất thải rắn thông thường ra môi trường tại thửa đất thuộc Cơ sở nuôi trồng thủy sản Thăng Tiến (xã Phước Hòa, huyện Phú Giáo). Sau đó, Hải tiến hành chôn, lấp tổng khối lượng 642.070 kg chất thải mà không được cơ quan nhà nước có thẩm quyền cho phép. Hành vi của Tô Văn Hải phạm vào tội “Gây ô nhiễm môi trường” theo điểm d khoản 3 Điều 235 Bộ luật Hình sự: “Chôn, lấp, đổ, thải ra môi trường trái pháp luật chất thải rắn thông thường 500.000 kilogam trở lên”. Ngày 21/3/2023, Cơ quan Cảnh sát điều tra Công an tỉnh Bình Dương thực hiện lệnh bắt bị can để tạm giam đối với Tô Văn Hải và tiếp tục củng cố, điều tra làm rõ theo quy định. Cơ sở nuôi trồng thủy sản Thăng Tiến (Cơ sở Thăng Tiến) hoạt động theo giấy chứng nhận đăng ký hộ kinh doanh do UBND huyện Phú Giáo cấp ngày 21/12/2016 cho ông Hoàng Xuân Quyết (sinh năm 1979). Ngày 7/11/2017, ông Quyết chuyển nhượng hai thửa đất trên cùng cơ sở Thăng Tiến, quyền khai thác đất san lấp, đất sét gạch cho Tô Văn Hải. Dự án có tổng diện tích 24.477 m2. Đến tháng 5/2020, Hải hoàn thành việc khai thác đất tại cơ sở, diện tích khai thác đất tại cơ sở khoảng 15.000 m2, độ sâu từ 7 - 8m để làm ao nuôi cá, trong đó phần đê đai, vách moong phía đông giáp với phần đất còn lại có dấu hiệu sạt lở, phải gia cố taluy, trồng cây xanh. Đến ngày 18/9/2020, Sở Tài nguyên và Môi trường ban hành Thông báo số 4144/TB-STNMT về việc hoàn công sau khi khai thác đất san lấp, đất sét gạch tại công trình dự án nuôi trồng thủy sản của Cơ sở Thăng Tiến, sau đó, Hải bắt đầu san lấp gia cố khu vực ao nuôi cá. Quá trình san lấp, Hải mua đất san lấp của một số cá nhân, cơ sở trên địa bàn huyện Phú Giáo để san lấp ao nuôi cá. Đồng thời, Hải cho một số cá nhân khác đổ số lượng lớn chất thải trên diện tích san lấp nhằm mục đích tiết kiệm chi phí mua vật liệu san lấp. Ngày 7/12/2022, Cơ quan Cảnh sát điều tra Công an tỉnh Bình Dương kết luận kiểm tra xác minh, ra Quyết định khởi tố vụ án hình sự gây ô nhiễm môi trường xảy ra tại Cơ sở nuôi trồng thủy sản Thăng Tiến. Viện Kiểm sát nhân dân huyện Phú Giáo đã phê chuẩn Quyết định khởi tố vụ án để điều tra về hành vi gây ô nhiễm môi trường xảy ra tại Cơ sở sản xuất muối Dương Thị Vân tại xã Tân Long, huyện Phú Giáo. Trước đó, Công an huyện Phú Giáo phối hợp với các đơn vị của Sở Tài nguyên và Môi trường, Phòng Cảnh sát Môi trường Công an tỉnhvà Công an thị xã Bến Cát phát hiện một máy đào đất đang hoạt động chôn lấp chất thải trái phép ở Cơ sở sản xuất muối Dương Thị Vân. Đoàn kiểm tra trưng cầu đơn vị chức năng tiến hành đo đạc. Kết quả cho thấy tổng diện tích chứa chất thải là 933 m2, gồm 9 điểm (3 điểm chôn chất thải, 6 điểm chất thải lộ thiên), thể tích 1.878 m3. Đoàn kiểm tra đã gửi mẫu khảo sát xác định khối lượng của 1 m3 chất thải được đổ, chôn lấp có khối lượng 1.160 kg. Tổng lượng chất thải đổ, chôn lấp tại cơ sở sản xuất Dương Thị Vân hơn 2.100 tấn gồm vải vụn, giày da vụn. Cơ quan Cảnh sát điều tra Công an tỉnh Bình Dương khuyến cáo, các cơ quan, tổ chức, người dân có nghĩa vụ thực hiện nghiêm các quy định của pháp luật về bảo vệ môi trường, tuyệt đối không thực hiện việc đổ, xả, thải ra môi trường các loại chất thải: chất thải rắn, khí thải, nước thải,… chưa qua xử lý. Các hành vi vi phạm tùy tính chất, mức độ sẽ bị xử lý hành chính từ phạt tiền đến xử lý hình sự đến 7 năm tù về tội “Gây ô nhiễm môi trường” theo Điều 235 Bộ luật Hình sự, đồng thời người vi phạm còn phải khắc phục hậu quả, khôi phục nguyên trạng môi trường theo quy định. Pháp nhân thương mại phạm tội có thể bị cấm kinh doanh, cấm hoạt động đến 3 năm và nộp tiền đến 20 tỷ đồng.'),
 ('c_2',
  '(PLO)- Theo Tổng Công ty Cấp nước Sài Gòn (SAWACO) việc cúp nước là để thực hiện công tác bảo trì, bảo dưỡng định kỳ Nhà máy nước Tân Hiệp. SAWACO cho biết đây là phương án để đảm bảo cung cấp nước sạch an toàn, liên tục phục vụ cho người dân TP. Vì vậy, SAWACO thông báo tạm ngưng cung cấp nước để thực hiện công tác nêu trên. Thời gian thực hiện dự kiến từ 22 giờ ngày 25-3 (thứ bảy) đến 4 giờ ngày 26-3 (chủ nhật). Các khu vực tạm ngưng cung cấp nước gồm quận 6, 8, 12, Gò Vấp, Tân Bình, Tân Phú, Bình Tân và huyện Hóc Môn, Bình Chánh. SAWACO cho biết do điều kiện đặc thù của vùng cung cấp nước nên thời gian phục hồi nước trên mạng lưới cấp nước tại một số nơi xa nguồn sẽ chậm hơn so với mốc thời gian chính nêu trên. Theo đó, để hạn chế đến mức thấp nhất ảnh hưởng đến sinh hoạt của người dân, SAWACO đã có phương án tăng cường cấp nước bằng xe bồn tại các khu vực trọng yếu; điều tiết hỗ trợ từ mạng truyền tải, theo dõi chặt chẽ diễn biến trên mạng lưới cấp nước để điều phối nguồn nước theo tình hình thực tế. Đồng thời, SAWACO chủ động phối hợp giải quyết các vấn đề phát sinh xảy ra trên mạng lưới cấp nước.'),
 ('c_3',
  'Với khoảng 200 thành viên, UEF Warm Hugs Club - một câu lạc bộ thiện nguyện thuộc Trường Đại học Kinh tế - Tài chính TP HCM (UEF) - đang ngày càng tạo được dấu ấn tích cực trong cộng đồng sinh viên UEF Warm Hugs Club được thành lập vào năm 2015 với sứ mệnh trao gửi yêu thương, giúp đỡ những mảnh đời bất hạnh, tiếp sức cho các em nhỏ đến trường. Thông điệp yêu thương Nguyễn Thảo Hương Quỳnh, Chủ nhiệm UEF Warm Hugs Club, cho biết mong muốn khi mọi người nhắc đến câu lạc bộ (CLB) là nghĩ ngay đến hình ảnh "Những cái ôm ấm áp" - nơi các bạn sinh viên tay khoác tay, vai kề vai phụng sự cộng đồng. "Khi trao những cái ôm, ta cảm nhận được nhịp đập của đối phương, từ đó thêm biết, thấu hiểu, sẻ chia cho khó khăn của người khác. Kim chỉ nam của chúng tôi là hết lòng giúp đỡ mọi người, tuy không nhiều nhưng ít nhất là vơi được phần nào gánh nặng lúc ngặt nghèo" - Hương Quỳnh tâm tình. Mỗi chuyến đi càng thắp sáng mạnh mẽ nguồn năng lượng, tinh thần và sự tích cực trong tim các bạn trẻ. (Ảnh do nhân vật cung cấp) Khi mới ra đời, CLB vỏn vẹn 4 bạn sinh viên năm nhất đầy sức trẻ, dưới sự ủng hộ và chỉ dẫn của thầy Phó Hiệu trưởng Ngô Cao Cường. Thời gian đầu hoạt động, CLB có lúc trên bờ vực tan rã vì số thành viên ít ỏi nhưng đã ngày càng lớn mạnh cùng nhiều dự án đậm tính nhân văn. UEF Warm Hugs Club không chỉ tăng quy mô mà còn là số chương trình thực hiện, đối tượng hướng đến, số địa phương đã đi qua và số học bổng trao đi. Hơn 30 chương trình từ thiện lớn nhỏ, 12 tỉnh, thành và hàng trăm em học sinh nghèo, cụ già neo đơn được chăm lo chính là niềm vui và sự tự hào của các sinh viên có tấm lòng thơm thảo này. Không ngại dấn bước Warm Hugs nổi tiếng với chương trình thiện nguyện thường niên mang tên "Nắng ấm biên cương" (NABC) đến nay đã trải qua 6 mùa. Là chương trình lớn nhất của CLB trong năm nên mọi thứ được chuẩn bị rất kỹ lưỡng, chỉn chu và cũng không ít lần gặp thử thách. Chẳng hạn, NABC mùa 4 gây quỹ không đủ khi chỉ còn cách ngày diễn ra sự kiện là 10 ngày. Song với khát khao được giúp đỡ mọi người và nghĩ đến những nụ cười của các em nhỏ, các thành viên đã nỗ lực hết sức để huy động đủ kinh phí. Mỗi lần thực hiện chương trình, ai cũng phải tập trung cao độ, dốc hết trái tim vì mục tiêu chung, tuyệt đối không được mang suy nghĩ "làm cho có", "tham gia CLB cho vui". Nhờ vậy, tập thể càng gắn kết và vượt qua được giới hạn rằng đây chỉ là CLB nhỏ trong trường đại học mà tự tin, kiên trì kiến tạo, theo đuổi các hoạt động ý nghĩa, thiết thực cho xã hội. Warm Hugs đậm chất trẻ trung, năng động sáng tạo và không kém phần chuyên nghiệp, bài bản. (Ảnh do nhân vật cung cấp) Cột mốc đáng nhớ là vào mùa NABC 5, Warm Hugs là CLB đầu tiên trong trường thực hiện chương trình từ thiện với số tiền hơn 130 triệu đồng từ việc kêu gọi tài trợ và bán hàng gây quỹ, trao hàng trăm phần quà cho các em nhỏ và cụ già neo đơn. Với các thành viên, phần thưởng đáng giá của họ là trưởng thành hơn, biết trân trọng các giá trị đáng quý trong đời, mở rộng tâm hồn đón nhận, học hỏi bao điều hay, biết cách quan tâm và bày tỏ tình cảm tốt đẹp đến người khác. "Thật may vì trên hành trình trao gửi yêu thương, tôi đã được đồng hành với những người bạn thật tuyệt vời. Với tôi, họ giàu trắc ẩn và dũng cảm, không ngại gian khó, sẵn sàng đi đến những vùng đất xa xôi để giúp đỡ người khác" - Hương Quỳnh xúc động kể. Những ánh mắt trong veo, những nụ cười rạng rỡ và cả những giọt nước mắt hạnh phúc đã tạo nên trải nghiệm đầy ý nghĩa trong quãng đời sinh viên của các bạn trẻ gen Z này. Và chuyến xe Warm Hugs sẽ tiếp tục lăn bánh đến nhiều nơi, lan tỏa yêu thương cho cộng đồng.'),
 ('c_4',

In [2]:
document_query_pairs = pd.read_csv('../../data/vifactcheck_document_query_pairs.tsv', sep='\t', header=None)

document_query_pairs.columns = ['document', 'query']
document_query_pairs.head()

,document,query
0,"(Chinhphu.vn) - Đây là mong muốn, gửi gắm của ...","Phó Thủ tướng Trần Hồng Hà thay mặt Chính phủ,..."
1,"Ngày 24/3, Cơ quan Cảnh sát điều tra Công an t...",Hành vi của Tô Văn Hải là cho phép người khác ...
2,(PLO)- Theo Tổng Công ty Cấp nước Sài Gòn (SAW...,SAWACO thông báo tạm ngưng cung cấp nước để th...
3,Chỉ một số ít nghệ sĩ được đứng trên sân khấu ...,"Để cảm ơn khi ai đó dành cho ta một lời khen, ..."
4,"Chiều 24-3, tại tứ kết Giải quần vợt M25 Luckn...",Lý Hoàng Nam đã chơi tự tin để quân bình tỉ số...

In [3]:
document_query_pairs = pd.read_csv('../../data/document_query_pairs.tsv', sep='\t', header=None)

document_query_pairs.columns = ['document', 'query']
document_query_pairs.head()

,document,query
0,"(Chinhphu.vn) - Đây là mong muốn, gửi gắm của ...","Phó Thủ tướng Trần Hồng Hà thay mặt Chính phủ,..."
1,"Ngày 24/3, Cơ quan Cảnh sát điều tra Công an t...",Hành vi của Tô Văn Hải là cho phép người khác ...
2,(PLO)- Theo Tổng Công ty Cấp nước Sài Gòn (SAW...,SAWACO thông báo tạm ngưng cung cấp nước để th...
3,Chỉ một số ít nghệ sĩ được đứng trên sân khấu ...,"Để cảm ơn khi ai đó dành cho ta một lời khen, ..."
4,"Chiều 24-3, tại tứ kết Giải quần vợt M25 Luckn...",Lý Hoàng Nam đã chơi tự tin để quân bình tỉ số...

In [4]:
document_query_pairs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25498 entries, 0 to 25497
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   document  25498 non-null  object
 1   query     25498 non-null  object
dtypes: object(2)
memory usage: 398.5+ KB