In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from datasets import load_dataset

vifactcheck = load_dataset("tranthaihoa/vifactcheck")

README.md:   0%|          | 0.00/853 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/8.07M [00:00<?, ?B/s]

data/dev-00000-of-00001.parquet:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/2.48M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/5062 [00:00<?, ? examples/s]

Generating dev split:   0%|          | 0/723 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1447 [00:00<?, ? examples/s]

In [3]:
viwikifc = "/content/drive/MyDrive/KLTN_Project/Datasets/ViWikiFC/train_final_pro.csv"
vinumfcr = "/content/drive/MyDrive/KLTN_Project/Datasets/ViNumFCR/Data_10008_gốc/train_evidence.jsonl"

In [4]:
import pandas as pd

viwikifc_df = pd.read_csv(viwikifc)
viwikifc_df.head()

,pairID,evidence,gold_label,link,context,sentenceID,claim,annotator_labels,title
0,uit_424_27_39_3_11,Chế độ quân chủ chuyên chế đã tỏ ra quá già cỗ...,Supports,https://vi.wikipedia.org/Trung Quốc,"Cuối thời nhà Thanh, do sự lạc hậu về khoa học...",uit_424_27_39_3,Chế độ quân chủ chuyên chế của nhà Thanh đã tỏ...,['Support'],Trung Quốc
1,uit_817_41_89_5_11,Một cuộc đảo chính lật đổ nền quân chủ và thàn...,Supports,https://vi.wikipedia.org/thế kỷ XX,1962: Khủng hoảng tên lửa Cuba. Algérie giành ...,uit_817_41_89_5,Đảo chính và lập ra chính quyền Cộng hòa Ả Rập...,['Support'],thế kỷ XX
2,uit_854_44_98_3_12,"Năm 1956, sau khi Pháp hoàn tất rút quân khỏi ...",Supports,https://vi.wikipedia.org/quần đảo Hoàng Sa,Năm 1954 - Hiệp định Genève quy định lấy vĩ tu...,uit_854_44_98_3,"Năm 1956, sau khi Pháp rút quân khỏi Việt Nam,...",['Support'],quần đảo Hoàng Sa
3,uit_948_53_29_11_12,Các hải tặc người Mã Lai và Dayak Biển từ hang...,Supports,https://vi.wikipedia.org/Borneo,"Từ khi Malacca thất thủ vào năm 1511, các thươ...",uit_948_53_29_11,Các tàu biển trên cuộc hành trình giữa Singapo...,['Support'],Borneo
4,uit_65_5_1_4_11,Singapore là quốc gia có mức độ đô thị hóa rất...,Supports,https://vi.wikipedia.org/Singapore,Singapore (phát âm: “Xin-ga-po” hoặc “Xinh-ga-...,uit_65_5_1_4,Singapore là một quốc gia mà ở đó có mức đô th...,['Support'],Singapore

In [5]:
vinumfcr_df = pd.read_json(vinumfcr, lines=True)
vinumfcr_df.head()

,paragraph,envidence start 4,envidence start 3,link,envidence start 2,annotator_labels,label,envidence start 1,envidence 1,envidence 2,envidence 3,envidence 4,context,sentenceID,topic,claim,pairID
0,Lần đầu tiên kể từ năm 2017 và là lần thứ hai ...,,,https://vnexpress.net/luc-si-viet-nam-vo-dich-...,101,[Supported],Supported,0,Lần đầu tiên kể từ năm 2017 và là lần thứ hai ...,"Bởi sáu năm trước ở Mỹ, Thạch Kim Tuấn cũng đo...",,,Lần đầu tiên kể từ năm 2017 và là lần thứ hai ...,uit_10695_1,Thể thao,"Võ sĩ người Việt Nam Thạch Kim Tuấn, một người...",uit_10695_1_1_10
1,Lần đầu tiên kể từ năm 2017 và là lần thứ hai ...,NaN,NaN,https://vnexpress.net/luc-si-viet-nam-vo-dich-...,NaN,[NotenoughInfo],NotenoughInfo,NaN,NaN,NaN,NaN,NaN,Lần đầu tiên kể từ năm 2017 và là lần thứ hai ...,uit_10695_1,Thể thao,"Theo thông tin từ cục An toàn thực phẩm, Sở Vă...",uit_10695_1_3_10
2,Kịch bản tương tự tái hiện ở giải thế giới ở A...,,,https://vnexpress.net/luc-si-viet-nam-vo-dich-...,148,[Supported],Supported,0,Kịch bản tương tự tái hiện ở giải thế giới ở A...,Còn Ngô Sơn Đỉnh giành cả ba HC bạc với tổng c...,,,Lần đầu tiên kể từ năm 2017 và là lần thứ hai ...,uit_10695_2,Thể thao,"Việt Nam đã vô địch ở Arab Saudi, khi Ngô Sơn ...",uit_10695_2_1_10
3,Kịch bản tương tự tái hiện ở giải thế giới ở A...,NaN,NaN,https://vnexpress.net/luc-si-viet-nam-vo-dich-...,NaN,[NotenoughInfo],NotenoughInfo,NaN,NaN,NaN,NaN,NaN,Lần đầu tiên kể từ năm 2017 và là lần thứ hai ...,uit_10695_2,Thể thao,Vụ xô xát ở Arab Saudi tiếp tục khiến một thí ...,uit_10695_2_3_10
4,"Gia Thành 25 tuổi, người Bắc Ninh, đã đoạt HC ...",,,https://vnexpress.net/luc-si-viet-nam-vo-dich-...,143,[Supported],Supported,0,"Gia Thành 25 tuổi, người Bắc Ninh, đã đoạt HC ...",Anh cũng là đô cử duy nhất của Việt Nam từng v...,,,Lần đầu tiên kể từ năm 2017 và là lần thứ hai ...,uit_10695_3,Thể thao,Đô cử duy nhất của Việt Nam Gia Thành vừa đoạt...,uit_10695_3_1_10